In [23]:
import numpy as np
import random

memory = []
maxlen = 10
idx = 0
for i in range(0,15):
    print('Append ',i)
    idx = idx % maxlen
    # Check capacity
    if (len(memory) < maxlen):
        memory += [(i)]
    else:
        memory[idx] = i
    # Append transition
    idx = idx + 1

    print(i,'th memory ',memory,len(memory))

print(memory)


Append  0
0 th memory  [0] 1
Append  1
1 th memory  [0, 1] 2
Append  2
2 th memory  [0, 1, 2] 3
Append  3
3 th memory  [0, 1, 2, 3] 4
Append  4
4 th memory  [0, 1, 2, 3, 4] 5
Append  5
5 th memory  [0, 1, 2, 3, 4, 5] 6
Append  6
6 th memory  [0, 1, 2, 3, 4, 5, 6] 7
Append  7
7 th memory  [0, 1, 2, 3, 4, 5, 6, 7] 8
Append  8
8 th memory  [0, 1, 2, 3, 4, 5, 6, 7, 8] 9
Append  9
9 th memory  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] 10
Append  10
10 th memory  [10, 1, 2, 3, 4, 5, 6, 7, 8, 9] 10
Append  11
11 th memory  [10, 11, 2, 3, 4, 5, 6, 7, 8, 9] 10
Append  12
12 th memory  [10, 11, 12, 3, 4, 5, 6, 7, 8, 9] 10
Append  13
13 th memory  [10, 11, 12, 13, 4, 5, 6, 7, 8, 9] 10
Append  14
14 th memory  [10, 11, 12, 13, 14, 5, 6, 7, 8, 9] 10
[10, 11, 12, 13, 14, 5, 6, 7, 8, 9]


In [17]:
import numpy as np
import random

class ReplayMemory():
    def __init__(self, capacity):
        self.capacity = capacity
        self.buffer = []
        self.buffer_idx = 0


    def append(self, transition:list):
        self.buffer_idx = self.buffer_idx % self.capacity
        if(len(self.buffer) < self.capacity):
            self.buffer += [transition]
        else:
            self.buffer[self.buffer_idx] = transition
        self.buffer_idx += 1

    def sample(self, n:int):
        return random.sample(self.buffer,n)

    def __len__(self):
        return len(self.buffer)

    def show(self):
        print(self.buffer)

maxlen = 10
memory = ReplayMemory(capacity=maxlen)
for i in range(0,15):
    print('Append ',i)
    memory.append((1,i))

    print(i+1,'th memory ',len(memory))
    memory.show()

print(memory.sample(1))
print(memory.sample(2))
print(memory.sample(3))
tmp = memory.sample(1)
print(tmp[0][1])

print('Sampling from memory')
mini_batch = memory.sample(5)
component_no = 2
print('Sample ',component_no,'-th component of transitions')
print(np.array([sample[component_no-1] for sample in mini_batch]))

Append  0
1 th memory  1
[(1, 0)]
Append  1
2 th memory  2
[(1, 0), (1, 1)]
Append  2
3 th memory  3
[(1, 0), (1, 1), (1, 2)]
Append  3
4 th memory  4
[(1, 0), (1, 1), (1, 2), (1, 3)]
Append  4
5 th memory  5
[(1, 0), (1, 1), (1, 2), (1, 3), (1, 4)]
Append  5
6 th memory  6
[(1, 0), (1, 1), (1, 2), (1, 3), (1, 4), (1, 5)]
Append  6
7 th memory  7
[(1, 0), (1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6)]
Append  7
8 th memory  8
[(1, 0), (1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7)]
Append  8
9 th memory  9
[(1, 0), (1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7), (1, 8)]
Append  9
10 th memory  10
[(1, 0), (1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7), (1, 8), (1, 9)]
Append  10
11 th memory  10
[(1, 10), (1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7), (1, 8), (1, 9)]
Append  11
12 th memory  10
[(1, 10), (1, 11), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7), (1, 8), (1, 9)]
Append  12
13 th memory  10
[(1, 10), (1, 11), (1, 12), (1, 3), (1, 4), (1, 5

In [6]:
import numpy as np
import random

class ReplayMemory():
    def __init__(self, capacity):
        self.capacity = capacity
        self.buffer = []
        self.buffer_idx = 0


    def append(self, transition:list):
        self.buffer_idx = self.buffer_idx % self.capacity
        if(len(self.buffer) < self.capacity):
            self.buffer += [transition]
        else:
            self.buffer[self.buffer_idx] = transition
        self.buffer_idx += 1

    def sample(self, n:int):
        return random.sample(self.buffer,n)

    # def sample_in_episode(self, n:int):
    #     return random.sample(self.buffer,n)

    def __len__(self):
        return len(self.buffer)

    def show(self):
        print(self.buffer)

# maxlen = 10
# memory = ReplayMemory(capacity=maxlen)
# for i in range(0,15):
#     print('Append ',i)
#     memory.append((1,i))

#     print(i+1,'th memory ',len(memory))
#     memory.show()

print('memory content ',memory.buffer)
print('sliced memory content ',memory.buffer[3:8])
# print(memory.sample(1))
# print(memory.sample(2))
# print(memory.sample(3))
# tmp = memory.sample(1)
# print(tmp[0][1])

# print('Sampling from memory')
# mini_batch = memory.sample(5)
# component_no = 2
# print('Sample ',component_no,'-th component of transitions')
# print(np.array([sample[component_no-1] for sample in mini_batch]))

memory content  [(1, 10), (1, 11), (1, 12), (1, 13), (1, 14), (1, 5), (1, 6), (1, 7), (1, 8), (1, 9)]
sliced memory content  [(1, 13), (1, 14), (1, 5), (1, 6), (1, 7)]


In [16]:
import numpy as np
import random
items1 = []
items2 = []
max_len = 5
n = 3
idxes = [random.randint(0, max_len-1) for _ in range(n)]
for i in range(7):
  item1 = np.array([[i, i]], dtype=np.float32)
  item2 = np.array([[i, i*i]], dtype=np.float32)
#   item1 = np.expand_dims(item1, axis=0)
#   item2 = np.expand_dims(item2, axis=0)
  if i is 0:
    items1 = item1
    items2 = item2
  elif i < max_len:
    items1 = np.append(items1, item1, axis=0)
    items2 = np.append(items2, item2, axis=0)
  else:
    idx = i % max_len
    items1[idx] = item1
    items2[idx] = item2
print(items1)
print(items2)
sample1 = items1[idxes]
sample2 = items2[idxes]
print(sample1, type(sample1))
print(sample2, type(sample2))

[[5. 5.]
 [6. 6.]
 [2. 2.]
 [3. 3.]
 [4. 4.]]
[[ 5. 25.]
 [ 6. 36.]
 [ 2.  4.]
 [ 3.  9.]
 [ 4. 16.]]
[[4. 4.]
 [2. 2.]
 [3. 3.]] <class 'numpy.ndarray'>
[[ 4. 16.]
 [ 2.  4.]
 [ 3.  9.]] <class 'numpy.ndarray'>


In [ ]:
import numpy as np
import random
items = dict{i:None for i in range(4)}
max_len = 5
n = 3
idxes = [random.randint(0, max_len-1) for _ in range(n)]
for i in range(7):
  item1 = np.array([[i, i]], dtype=np.float32)
  item2 = np.array([[i, i*i]], dtype=np.float32)
#   item1 = np.expand_dims(item1, axis=0)
#   item2 = np.expand_dims(item2, axis=0)
  if i is 0:
    items1 = item1
    items2 = item2
  elif i < max_len:
    items1 = np.append(items1, item1, axis=0)
    items2 = np.append(items2, item2, axis=0)
  else:
    idx = i % max_len
    items1[idx] = item1
    items2[idx] = item2
print(items1)
print(items2)
sample1 = items1[idxes]
sample2 = items2[idxes]
print(sample1, type(sample1))
print(sample2, type(sample2))

In [41]:
import numpy as np
import random
# items = dict({"i":None} for i in range(4))
# print(items)
n = 2
idxes = [random.randint(0, 3-1) for _ in range(n)]
items = dict()
items[0] = None
items[1] = None
items[2] = None
items[3] = None
items[4] = None

items[0] = np.array([[0,2],[0,3],[0,4]])
items[1] = np.array([[1,2],[1,3],[1,4]])
items[2] = np.array([[2,2],[2,3],[2,4]])
items[3] = np.array([[3,2],[3,3],[3,4]])
items[4] = np.array([[4,2],[4,3],[4,4]])
print('item[0] - ',items[0])
print('idxes - ',idxes)
print(items[0][0])
print('item[0][idxes] - ',items[0][idxes])
print([items[i][idxes] for i in range(5)])
print([i for i in range(5)])


item[0] -  [[0 2]
 [0 3]
 [0 4]]
idxes -  [2, 1]
[0 2]
item[0][idxes] -  [[0 4]
 [0 3]]
[array([[0, 4],
       [0, 3]]), array([[1, 4],
       [1, 3]]), array([[2, 4],
       [2, 3]]), array([[3, 4],
       [3, 3]]), array([[4, 4],
       [4, 3]])]
[0, 1, 2, 3, 4]


In [48]:
import numpy as np

temp = np.zeros((1,2,2,2))
print(temp)
shapes = np.shape(temp)
print(shapes)
length = 1000
shapes.insert(0,length)
print(temp)
temp1 = np.zeros(temp)

[[[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]]
(1, 2, 2, 2)


AttributeError: 'numpy.ndarray' object has no attribute 'insert'